# Generated by Django 2.0.5 on 2018-07-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneOff',
        ),
        migrations.DeleteModel(
            name='ReOccuring',
        ),
    ]
