# Generated by Django 2.0.5 on 2018-08-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20180730_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbasic',
            name='num_passenger',
        ),
    ]
