# Generated by Django 2.0.5 on 2018-08-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_formbasic_num_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbasic',
            name='num_passenger',
            field=models.IntegerField(default=1),
        ),
    ]
