# Generated by Django 2.0.5 on 2018-08-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_formbasic_num_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formbasic',
            old_name='num_passenger',
            new_name='number_of_passengers',
        ),
    ]
