# Generated by Django 2.0.5 on 2018-08-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20180802_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbasic',
            name='birthdate',
            field=models.DateField(max_length=8),
        ),
    ]
