# Generated by Django 2.0.5 on 2018-08-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_auto_20180802_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbasic',
            name='birthdate',
            field=models.CharField(max_length=8),
        ),
    ]
