# Generated by Django 2.0.5 on 2018-08-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_formbasic_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbasic',
            name='appointment_date',
            field=models.DateTimeField(default='', max_length=8),
        ),
    ]
