# Generated by Django 2.0.5 on 2018-08-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_auto_20180804_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbasic',
            name='pickup_address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='pickup_time',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='return_address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='return_time',
            field=models.CharField(max_length=3),
        ),
    ]
