# Generated by Django 2.0.5 on 2018-08-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_auto_20180804_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reoccuring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('birthdate', models.CharField(max_length=8)),
                ('patient_med_number', models.CharField(max_length=30)),
                ('number_of_passengers', models.IntegerField(default=1)),
                ('start_date', models.CharField(max_length=12)),
                ('emd_date', models.CharField(max_length=12)),
                ('pickup_time1', models.CharField(max_length=12)),
                ('return_time1', models.CharField(max_length=12)),
                ('pickup_time2', models.CharField(max_length=12)),
                ('return_time2', models.CharField(max_length=12)),
                ('pickup_time3', models.CharField(max_length=12)),
                ('return_time3', models.CharField(max_length=12)),
                ('pickup_time4', models.CharField(max_length=12)),
                ('return_time4', models.CharField(max_length=12)),
                ('pickup_time5', models.CharField(max_length=12)),
                ('return_time5', models.CharField(max_length=12)),
                ('pickup_time6', models.CharField(max_length=12)),
                ('return_time6', models.CharField(max_length=12)),
                ('pickup_time7', models.CharField(max_length=12)),
                ('return_time7', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='appointment_date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='pickup_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='return_time',
            field=models.CharField(max_length=10),
        ),
    ]
