# Generated by Django 2.0.5 on 2018-08-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_auto_20180804_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reoccuring',
            old_name='emd_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reoccuring',
            old_name='pickup_time2',
            new_name='pickup_day1',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='pickup_time3',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='pickup_time4',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='pickup_time5',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='pickup_time6',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='pickup_time7',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='return_time2',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='return_time3',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='return_time4',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='return_time5',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='return_time6',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='return_time7',
        ),
        migrations.AddField(
            model_name='reoccuring',
            name='pickup_address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reoccuring',
            name='return_address',
            field=models.CharField(default='', max_length=30),
        ),
    ]
