# Generated by Django 2.0.5 on 2018-08-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_reoccuring_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reoccuring',
            old_name='pickup_day1',
            new_name='pickup_day_one',
        ),
        migrations.RenameField(
            model_name='reoccuring',
            old_name='pickup_time1',
            new_name='pickup_time_one',
        ),
        migrations.RenameField(
            model_name='reoccuring',
            old_name='return_time1',
            new_name='return_time_one',
        ),
    ]
