# Generated by Django 2.0.6 on 2018-08-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_auto_20180804_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reoccuring',
            old_name='pickup_address',
            new_name='pickup_address_one',
        ),
        migrations.RenameField(
            model_name='reoccuring',
            old_name='return_address',
            new_name='pickup_address_two',
        ),
        migrations.RemoveField(
            model_name='reoccuring',
            name='pickup_day_one',
        ),
        migrations.AddField(
            model_name='reoccuring',
            name='pickup_time_two',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='reoccuring',
            name='return_address_one',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reoccuring',
            name='return_address_two',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reoccuring',
            name='return_time_two',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='reoccuring',
            name='weekday_one',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='reoccuring',
            name='weekday_two',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='reoccuring',
            name='number_of_passengers',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='reoccuring',
            name='pickup_time_one',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='reoccuring',
            name='return_time_one',
            field=models.CharField(default='', max_length=12),
        ),
    ]
