# Generated by Django 2.0.6 on 2018-08-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_auto_20180806_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reoccuring',
            old_name='return_address_one',
            new_name='destination_address_one',
        ),
        migrations.RenameField(
            model_name='reoccuring',
            old_name='return_address_two',
            new_name='destination_address_two',
        ),
    ]
