# Generated by Django 2.0.6 on 2018-08-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_auto_20180807_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbasic',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reoccuring',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
