# Generated by Django 2.0.6 on 2018-08-09 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0021_auto_20180807_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formbasic',
            old_name='return_address',
            new_name='destination_address',
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
