# Generated by Django 2.0.5 on 2018-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0022_auto_20180809_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formbasic',
            old_name='birthdate',
            new_name='patient_birthdate',
        ),
        migrations.RenameField(
            model_name='formbasic',
            old_name='name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='formbasic',
            old_name='phone',
            new_name='patient_phone',
        ),
        migrations.RenameField(
            model_name='reoccuring',
            old_name='birthdate',
            new_name='patient_birthdate',
        ),
        migrations.RenameField(
            model_name='reoccuring',
            old_name='name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='reoccuring',
            old_name='phone',
            new_name='patient_phone',
        ),
        migrations.AddField(
            model_name='formbasic',
            name='account_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='formbasic',
            name='call_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='formbasic',
            name='service_type',
            field=models.CharField(default='', max_length=15),
        ),
    ]
