# Generated by Django 2.0.5 on 2018-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0023_auto_20180811_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbasic',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='destination_address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='pickup_address',
            field=models.CharField(max_length=80),
        ),
    ]
