# Generated by Django 2.0.5 on 2018-08-12 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0024_auto_20180811_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reoccuring',
            new_name='Reocurring',
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='destination_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='pickup_address',
            field=models.CharField(max_length=200),
        ),
    ]
