# Generated by Django 2.0.5 on 2018-08-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0025_auto_20180812_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reocurring',
            name='pickup_address_two',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
