# Generated by Django 2.0.5 on 2018-08-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0026_auto_20180812_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reocurring',
            name='destination_address_two',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='pickup_time_two',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='return_time_two',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='weekday_two',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
