# Generated by Django 2.0.6 on 2018-08-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0028_auto_20180812_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reocurring',
            old_name='end_date',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='reocurring',
            name='start_date',
        ),
    ]
