# Generated by Django 2.0.5 on 2018-08-17 20:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0031_auto_20180817_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reocurring',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thur', 'Thur')], max_length=16, null=True),
        ),
    ]
