# Generated by Django 2.0.5 on 2018-08-18 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0033_auto_20180817_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reocurring',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
