# Generated by Django 2.0.5 on 2018-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0034_auto_20180818_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='reocurring',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
    ]
