# Generated by Django 2.0.5 on 2018-08-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0035_reocurring_round_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbasic',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='reocurring',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='formbasic',
            name='patient_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='formbasic',
            name='patient_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reocurring',
            name='patient_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reocurring',
            name='patient_last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='destination_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
