# Generated by Django 2.0.5 on 2018-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0036_auto_20180820_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reocurring',
            name='number_of_passengers',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
