# Generated by Django 2.0.5 on 2018-08-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0039_formbasic_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbasic',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='reocurring',
            name='patient_gender',
        ),
        migrations.AddField(
            model_name='formbasic',
            name='is_the_patient_male',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reocurring',
            name='is_the_patient_male',
            field=models.BooleanField(default=True),
        ),
    ]
