# Generated by Django 2.0.5 on 2018-08-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0040_auto_20180821_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbasic',
            name='is_the_patient_male',
        ),
        migrations.RemoveField(
            model_name='reocurring',
            name='is_the_patient_male',
        ),
        migrations.AddField(
            model_name='formbasic',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='reocurring',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=1),
        ),
    ]
