# Generated by Django 2.0.5 on 2018-08-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0042_auto_20180822_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbasic',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=1),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=1),
        ),
    ]
