# Generated by Django 2.0.5 on 2018-08-25 01:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0044_auto_20180822_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reocurring',
            name='destination_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='end_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='pickup_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='pickup_time',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='return_time',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='start_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thur', 'Thur'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], default='', max_length=28),
        ),
    ]
