# Generated by Django 2.0.5 on 2018-08-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0047_auto_20180827_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbasic',
            name='call_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='formbasic',
            name='patient_med_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='call_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='patient_med_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
