# Generated by Django 2.0.5 on 2018-08-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0048_auto_20180827_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbasic',
            name='service_type',
            field=models.CharField(choices=[('SCFHP Basic', 'SCFHP Basic'), ('SCFHP Bariatric', 'SCFHP Bariatric'), ('SCFHP Ambulatory', 'SCFHP Ambulatory'), ('VMC Wheelchair', 'VMC Wheelchair'), ('VMC Ambulatory', 'VMC Ambulatory'), ('VMC Discharge', 'VMC Discharge'), ('VMC Bariatric', 'VMC Bariatric'), ('HERMAN Wheelchair', 'HERMAN Wheelchair'), ('HERMAN Ambulatory', 'HERMAN Ambulatory'), ('HERMAN Bariatric', 'HERMAN Bariatric')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='reocurring',
            name='service_type',
            field=models.CharField(choices=[('SCFHP Basic', 'SCFHP Basic'), ('SCFHP Bariatric', 'SCFHP Bariatric'), ('SCFHP Ambulatory', 'SCFHP Ambulatory'), ('VMC Wheelchair', 'VMC Wheelchair'), ('VMC Ambulatory', 'VMC Ambulatory'), ('VMC Discharge', 'VMC Discharge'), ('VMC Bariatric', 'VMC Bariatric'), ('HERMAN Wheelchair', 'HERMAN Wheelchair'), ('HERMAN Ambulatory', 'HERMAN Ambulatory'), ('HERMAN Bariatric', 'HERMAN Bariatric')], default='', max_length=15),
        ),
    ]
