# Generated by Django 2.0.5 on 2018-09-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0049_auto_20180830_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbasic',
            name='diagnostic_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reocurring',
            name='diagnostic_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
