# Generated by Django 2.1.1 on 2018-09-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0051_auto_20180902_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbasic',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reocurring',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
