# Generated by Django 2.1.1 on 2018-09-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0052_auto_20180907_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbasic',
            name='dl_user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reocurring',
            name='dl_user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
