# Generated by Django 2.1.1 on 2018-09-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0055_auto_20180908_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbasic',
            name='dl_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reocurring',
            name='dl_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
